### Get all filieres
GET http://localhost/restful_API/backend/route/filiereRoute.php

### Get filiere by ID
GET http://localhost/restful_API/backend/route/filiereRoute.php?id=1

### Create new filiere
POST http://localhost/restful_API/backend/route/filiereRoute.php
Content-Type: application/json

{
    "nom_filiere": "Génie Informatique",
    "id_chef_filiere": "2",
    "id_dep": "1",
    "niveau": "Master"
}

### Update filiere
PUT http://localhost/restful_API/backend/route/filiereRoute.php?id=1
Content-Type: application/json

{
    "nom_filiere": "Génie Logiciel",
    "id_chef_filiere": "2",
    "id_dep": "1",
    "niveau": "Licence"
}

### Delete filiere
DELETE http://localhost/restful_API/backend/route/filiereRoute.php?id=1