PUT http://localhost/Restful_API/backend/route/adminRoute.php?cni=CNI457
Content-Type: application/json;

{
    "id_admin": "100",
    "CNI": "CNI457",
    "nom": "chiboub",
    "prenom": "AHmed",
    "email": "sarsa.benni@univ.ma",
    "tele": "06234567890",
    "date_naissance": "1999-02-14",
    "lieu_naissance": "F\u00e8s",
    "sexe": "f\u00e9minin",
    "ville": "Taza",
    "pays": "Maroc",
    "date_debut_travail": "2024-03-20"
}